### PR TITLE
Allow react 18 in peerDependencies

### PR DESCRIPTION
**Pull request by chentsulin**
React 18 has been officially released: https://reactjs.org/blog/2022/03/29/react-v18.html

### CODE REVIEW

**Review by sametirkoren — APPROVED** [review]

**Comment by fengluo1** [comment]
Ping @bvaughn  @sametirkoren

**Comment by costvin15** [comment]
Hi @sametirkoren, can you review it?

**Comment by matthew-mcdermott** [comment]
+1

**Comment by MGMehdi** [comment]
Bump

**Comment by klausbreyer** [comment]
please  @bvaughn @sametirkoren @shhnjk , we also need it!

**Comment by mwanago** [comment]
@chentsulin @sametirkoren Hi. Is there any reason not to merge this and create a new release?

**Comment by cstephens-cni** [comment]
@bvaughn wanted to pump this to you.  I assume this isn't causing anyone any major issues.  But like many, this is our only non dev-dependency throwing warnings.  If you can let us know what the plan is I'm sure it would let us all set expectations.

**Comment by balthazar** [comment]
Considering the package doesn't seem to have been maintained for a while (not complaining, I know how hard it is to keep up), I created [a fork](https://github.com/Ashlar/react-virtualized-auto-sizer) and published it under `@ashlar-packages/react-virtualized-auto-sizer` (1.0.7) which might be of use to people while we await upstream to be updated.

**Comment by josempineiro** [comment]
@balthazar where have you published it?

**Comment by jlarmstrongiv** [comment]
Workaround for npm via overrides:
```json
{
  "overrides": {
    "react-virtualized-auto-sizer": {
      "react": "^18.0.0",
      "react-dom": "^18.0.0"
    }
  }
}
```

**Comment by bvaughn** [comment]
v1.0.7 just published with 18-rc+

**Pull request closed without merging**
