### PR TITLE
Bump react version to 17 in peerDependencies

### PR DESCRIPTION
**Pull request by raon0211**
There were no issues when using this library with React 17.

### CODE REVIEW

**Comment by stee-ren** [comment]
Any chance this PR can be approved? I want to use this in conjunction with react-window (which is awesome) but I can't because we're already on React 17.

**Comment by waynemock** [comment]
I agree with @stee-ren and @raon0211, let's get this PR approved. I'm on React 17 too. Any way to speed this up? Need any help?

**Comment by rehevkor5** [comment]
It looks like this can be closed because it's already that way in 1.0.6 https://github.com/bvaughn/react-virtualized-auto-sizer/blob/master/package.json#L57

**Comment by bvaughn** [comment]
v1.0.7 just published with 18-rc+

**Pull request closed without merging**
