### PR TITLE
Support react v17

### PR DESCRIPTION
**Pull request by moritzmhmk**
Added 17.0.0 to the possible versions of react in the peer dependencies. Tested in a project with react v17 and works fine!

### CODE REVIEW

**Comment by stee-ren** [comment]
Can this please be Merged - I would really love to use this module, but I can't exactly roll a large corporate project backwards to support this.

**Comment by codemaster3000** [comment]
+1 for merge !

**Review by codemaster3000 — APPROVED** [review]

**Comment by nattapon4erudite** [comment]
Is it finished merging yet? I still have an error.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0-alpha" from react-virtualized-auto-sizer@1.0.4
npm ERR! node_modules/react-virtualized-auto-sizer
npm ERR!   react-virtualized-auto-sizer@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by samuelgoldenbaum** [comment]
Can we please get this merged

**Comment by silltho** [comment]
@bvaughn can you take a look at this?

**Comment by bvaughn** [comment]
I don't really have the time to stay on top of projects like this. Another maintainer would be welcome.

**Comment by bvaughn** [comment]
Published as 1.0.5

**Comment by silltho** [comment]
@bvaughn Thank you. ❤️ 

> I don't really have the time to stay on top of projects like this. Another maintainer would be welcome.

That's understandable. 

I believe there are a lot of people with willingness to help. Would you mind activating issues? It would make searching a lot easier. I'm also be available if needed.

**Comment by bvaughn** [comment]
I'm not ready to be pinged by name on issues. (That happens _often_.)

**Pull request merged**
